services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    networks:
      - GigForge-Network
    volumes:
      - database-GigForge:/var/lib/postgresql/data

  mongodb:
    image: mongo
    restart: always
    networks:
      - GigForge-Network
    volumes:
      - database-GigForge:/data/db
    ports:
      - 27018:27017
  
  rabbitmq:
    image: rabbitmq:3.8-management
    restart: on-failure
    networks:
      - GigForge-Network
    volumes:
      - database-GigForge:/data/rabbitmq
    ports:
      - 5672:5672

  api-gateway: 
    image: muhamedjasim/gigforge-api_gateway
    build: ./API-Gateway/
    restart: on-failure
    environment:
      AUTH_SVC: "user-svc:30001"
      JOB_SVC: "job-svc:30003"
      Project_SVC: "project-svc:30004"
    networks:
      - GigForge-Network
    ports:
      - "3000:3000"

  user-svc:
    image: muhamedjasim/gigforge-user_svc:latest
    build: User-svc/
    restart: on-failure
    environment:
      DB_URL: "postgres://postgres:postgres@postgres:5432"
    depends_on:
      - postgres
    networks:
      - GigForge-Network
  

  job-svc:
    image: muhamedjasim/gigforge-job_svc:latest
    build: Job-svc/
    restart: on-failure
    environment:
      DB_URL: "postgres://postgres:postgres@postgres:5432"
    depends_on:
      - postgres
    networks:
      - GigForge-Network
     

  project-svc:
    image: muhamedjasim/gigforge-project_svc:latest
    build: project-svc/
    restart: on-failure
    environment:
      DB_URL: "postgres://postgres:postgres@postgres:5432"
    depends_on:
      - postgres
    networks:
      - GigForge-Network
  

  chat-svc:
    image: muhamedjasim/gigforge-chat_svc:latest
    build: chat-svc/
    restart: on-failure
    environment:
      mongoURL: mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - GigForge-Network
 

volumes:
  database-GigForge:

networks:
  GigForge-Network:
    driver: bridge