version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    networks:
      - GigForge-Network
    volumes:
      - gigforge_volume:/var/lib/postgresql/data

  mongodb:
    image: mongo
    restart: on-failure
    networks:
      - GigForge-Network
    volumes:
      - gigforge_volume:/data/db
    ports:
      - 27017:27017

  api-gateway: 
    image: api-gateway
    restart: on-failure
    environment:
      AUTH_SVC: "user-svc:30001"
      JOB_SVC: "job-svc:30003"
      Project_SVC: "project-svc:30004"
    networks:
      - GigForge-Network
    ports:
      - "3000:3000"

  user-svc:
    image: user-svc
    restart: on-failure
    environment:
      DB_URL: "postgres://postgres:postgres@postgres:5432"
    depends_on:
      - postgres
    networks:
      - GigForge-Network
  

  job-svc:
    image: job-svc
    restart: on-failure
    environment:
      DB_URL: "postgres://postgres:postgres@postgres:5432"
    depends_on:
      - postgres
    networks:
      - GigForge-Network
     

  project-svc:
    image: project-svc
    restart: on-failure
    environment:
      DB_URL: "postgres://postgres:postgres@postgres:5432"
    depends_on:
      - postgres
    networks:
      - GigForge-Network
  

  # chat-svc:
  #   image: chat-svc
  #   restart: on-failure
  #   environment:
  #     DB_URL: "postgres://postgres:postgres@postgres:5432"
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - GigForge-Network
 

volumes:
  database-postgres:

networks:
  GigForge-Network:
    driver: bridge