apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: gigforge-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gigforge-api-gateway
  template:
    metadata:
      labels:
        app: gigforge-api-gateway
    spec:
      containers:
      - name: gigforge-api-gateway
        image: muhamedjasim/gigforge-api_gateway:latest
        ports:
        - containerPort: 3000
        env:
        - name: AUTH_SVC
          valueFrom:
            secretKeyRef:
              name: gigforge-secret
              key: user-url
        - name: Job_SVC
          valueFrom:
            secretKeyRef:
              name: gigforge-secret
              key: job-url
        - name: Project_SVC
          valueFrom:
            secretKeyRef:
              name: gigforge-secret
              key: project-url
        - name: CHAT_SVC
          valueFrom:
            secretKeyRef:
              name: gigforge-secret
              key: chat-url
        - name: ATokenSecret
          valueFrom:
            secretKeyRef:
              name: gigforge-secret
              key: token-secret
        - name: PORT
          value: :3000
---

apiVersion: v1
kind: Service
metadata:
  name: gigforge-api-gateway-service
spec:
  type: ClusterIP
  selector:
    app: gigforge-api-gateway
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000