apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gigforge-certificate
  namespace: gigforge
spec:
  dnsNames:
    - gigforge.jasim.online
  secretName: gigforge-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
