apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-svc-deployment
  labels:
    app: gigforge-chat-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gigforge-chat-svc
  template:
    metadata:
      labels:
        app: gigforge-chat-svc
    spec:
      containers:
      - name: gigforge-chat-svc
        image: muhamedjasim/gigforge-chat_svc:1.0
        ports:
        - containerPort: 30005
        env:
        - name: mongoURL
          valueFrom: 
            secretKeyRef: 
              name: gigforge-secret
              key: mongo-url
        - name: amqpUrl
          valueFrom: 
            secretKeyRef: 
              name: gigforge-secret
              key: rabbitmq-url
        - name: PORT
          value: :30005
        
---

apiVersion: v1
kind: Service
metadata:
  name: gigforge-chat-svc-service
spec:
  type: ClusterIP
  selector:
    app: gigforge-chat-svc
  ports:
    - protocol: TCP
      port: 30005
      targetPort: 30005
