apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-svc-deployment
  labels:
    app: gigforge-job-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gigforge-job-svc
  template:
    metadata:
      labels:
        app: gigforge-job-svc
    spec:
      containers:
      - name: gigforge-job-svc
        image: muhamedjasim/gigforge-job_svc:1.0
        ports:
        - containerPort: 30003
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: gigforge-secret
              key: postgres-url
        - name: USER_SVC
          valueFrom:
            secretKeyRef:
              name: gigforge-secret
              key: user-url
        - name: PORT
          value: :30003
---

apiVersion: v1
kind: Service
metadata:
  name: gigforge-job-svc-service
spec:
  type: ClusterIP
  selector:
    app: gigforge-job-svc
  ports:
    - protocol: TCP
      port: 30003
      targetPort: 30003