// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: pb/auth/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	Login(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*UserLoginRes, error)
	Signup(ctx context.Context, in *UserSignupReq, opts ...grpc.CallOption) (*UserSignupRes, error)
	Verify(ctx context.Context, in *VerifyReq, opts ...grpc.CallOption) (*VerifyRes, error)
	ForgotPassword(ctx context.Context, in *FPreq, opts ...grpc.CallOption) (*FPres, error)
	ResetPassword(ctx context.Context, in *RPreq, opts ...grpc.CallOption) (*RPres, error)
	AddProfileDescription(ctx context.Context, in *APDReq, opts ...grpc.CallOption) (*APDRes, error)
	UpdateProfileDescription(ctx context.Context, in *UPDReq, opts ...grpc.CallOption) (*UPDRes, error)
	AddEducation(ctx context.Context, in *AddEducationReq, opts ...grpc.CallOption) (*AddEducationRes, error)
	UpdateEducation(ctx context.Context, in *UpdateEducationReq, opts ...grpc.CallOption) (*UpdateEducationRes, error)
	DeleteEducation(ctx context.Context, in *DeleteEducationReq, opts ...grpc.CallOption) (*DeleteEducationRes, error)
	GetProfile(ctx context.Context, in *GetProfileReq, opts ...grpc.CallOption) (*GetProfileRes, error)
	EditSkill(ctx context.Context, in *EditSkillReq, opts ...grpc.CallOption) (*EditSkillRes, error)
	AddExperience(ctx context.Context, in *ExpReq, opts ...grpc.CallOption) (*ExpRes, error)
	UpdateExperience(ctx context.Context, in *ExpReq, opts ...grpc.CallOption) (*ExpRes, error)
	DeleteExperience(ctx context.Context, in *DltExpReq, opts ...grpc.CallOption) (*DltExpRes, error)
	GetProfileClient(ctx context.Context, in *ClientProfileReq, opts ...grpc.CallOption) (*ClientProfileRes, error)
	BlockUser(ctx context.Context, in *BlockReq, opts ...grpc.CallOption) (*BlockRes, error)
	UnBlockUser(ctx context.Context, in *BlockReq, opts ...grpc.CallOption) (*BlockRes, error)
	AddSkill(ctx context.Context, in *AddSkillReq, opts ...grpc.CallOption) (*AddSkillRes, error)
	AdminLogin(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error)
	UpdateProfilePhoto(ctx context.Context, in *PhotoReq, opts ...grpc.CallOption) (*PhotoRes, error)
	OnboardFreelancerToPaypal(ctx context.Context, in *OnboardToPaypalReq, opts ...grpc.CallOption) (*OnboardToPaypalRes, error)
	ReviewFreelancer(ctx context.Context, in *ReviewFlancerReq, opts ...grpc.CallOption) (*ReviewFlancerRes, error)
	AddPaymentEmail(ctx context.Context, in *AddPaymentEmailReq, opts ...grpc.CallOption) (*AddPaymentEmailRes, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Login(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*UserLoginRes, error) {
	out := new(UserLoginRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Signup(ctx context.Context, in *UserSignupReq, opts ...grpc.CallOption) (*UserSignupRes, error) {
	out := new(UserSignupRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Verify(ctx context.Context, in *VerifyReq, opts ...grpc.CallOption) (*VerifyRes, error) {
	out := new(VerifyRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ForgotPassword(ctx context.Context, in *FPreq, opts ...grpc.CallOption) (*FPres, error) {
	out := new(FPres)
	err := c.cc.Invoke(ctx, "/auth.AuthService/ForgotPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ResetPassword(ctx context.Context, in *RPreq, opts ...grpc.CallOption) (*RPres, error) {
	out := new(RPres)
	err := c.cc.Invoke(ctx, "/auth.AuthService/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) AddProfileDescription(ctx context.Context, in *APDReq, opts ...grpc.CallOption) (*APDRes, error) {
	out := new(APDRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/AddProfileDescription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateProfileDescription(ctx context.Context, in *UPDReq, opts ...grpc.CallOption) (*UPDRes, error) {
	out := new(UPDRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/UpdateProfileDescription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) AddEducation(ctx context.Context, in *AddEducationReq, opts ...grpc.CallOption) (*AddEducationRes, error) {
	out := new(AddEducationRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/AddEducation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateEducation(ctx context.Context, in *UpdateEducationReq, opts ...grpc.CallOption) (*UpdateEducationRes, error) {
	out := new(UpdateEducationRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/UpdateEducation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DeleteEducation(ctx context.Context, in *DeleteEducationReq, opts ...grpc.CallOption) (*DeleteEducationRes, error) {
	out := new(DeleteEducationRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/DeleteEducation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetProfile(ctx context.Context, in *GetProfileReq, opts ...grpc.CallOption) (*GetProfileRes, error) {
	out := new(GetProfileRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/GetProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) EditSkill(ctx context.Context, in *EditSkillReq, opts ...grpc.CallOption) (*EditSkillRes, error) {
	out := new(EditSkillRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/EditSkill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) AddExperience(ctx context.Context, in *ExpReq, opts ...grpc.CallOption) (*ExpRes, error) {
	out := new(ExpRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/AddExperience", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateExperience(ctx context.Context, in *ExpReq, opts ...grpc.CallOption) (*ExpRes, error) {
	out := new(ExpRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/UpdateExperience", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DeleteExperience(ctx context.Context, in *DltExpReq, opts ...grpc.CallOption) (*DltExpRes, error) {
	out := new(DltExpRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/DeleteExperience", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetProfileClient(ctx context.Context, in *ClientProfileReq, opts ...grpc.CallOption) (*ClientProfileRes, error) {
	out := new(ClientProfileRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/GetProfileClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) BlockUser(ctx context.Context, in *BlockReq, opts ...grpc.CallOption) (*BlockRes, error) {
	out := new(BlockRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/BlockUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UnBlockUser(ctx context.Context, in *BlockReq, opts ...grpc.CallOption) (*BlockRes, error) {
	out := new(BlockRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/UnBlockUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) AddSkill(ctx context.Context, in *AddSkillReq, opts ...grpc.CallOption) (*AddSkillRes, error) {
	out := new(AddSkillRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/AddSkill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) AdminLogin(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error) {
	out := new(LoginRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/AdminLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateProfilePhoto(ctx context.Context, in *PhotoReq, opts ...grpc.CallOption) (*PhotoRes, error) {
	out := new(PhotoRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/UpdateProfilePhoto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) OnboardFreelancerToPaypal(ctx context.Context, in *OnboardToPaypalReq, opts ...grpc.CallOption) (*OnboardToPaypalRes, error) {
	out := new(OnboardToPaypalRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/OnboardFreelancerToPaypal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ReviewFreelancer(ctx context.Context, in *ReviewFlancerReq, opts ...grpc.CallOption) (*ReviewFlancerRes, error) {
	out := new(ReviewFlancerRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/ReviewFreelancer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) AddPaymentEmail(ctx context.Context, in *AddPaymentEmailReq, opts ...grpc.CallOption) (*AddPaymentEmailRes, error) {
	out := new(AddPaymentEmailRes)
	err := c.cc.Invoke(ctx, "/auth.AuthService/AddPaymentEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility
type AuthServiceServer interface {
	Login(context.Context, *UserLoginReq) (*UserLoginRes, error)
	Signup(context.Context, *UserSignupReq) (*UserSignupRes, error)
	Verify(context.Context, *VerifyReq) (*VerifyRes, error)
	ForgotPassword(context.Context, *FPreq) (*FPres, error)
	ResetPassword(context.Context, *RPreq) (*RPres, error)
	AddProfileDescription(context.Context, *APDReq) (*APDRes, error)
	UpdateProfileDescription(context.Context, *UPDReq) (*UPDRes, error)
	AddEducation(context.Context, *AddEducationReq) (*AddEducationRes, error)
	UpdateEducation(context.Context, *UpdateEducationReq) (*UpdateEducationRes, error)
	DeleteEducation(context.Context, *DeleteEducationReq) (*DeleteEducationRes, error)
	GetProfile(context.Context, *GetProfileReq) (*GetProfileRes, error)
	EditSkill(context.Context, *EditSkillReq) (*EditSkillRes, error)
	AddExperience(context.Context, *ExpReq) (*ExpRes, error)
	UpdateExperience(context.Context, *ExpReq) (*ExpRes, error)
	DeleteExperience(context.Context, *DltExpReq) (*DltExpRes, error)
	GetProfileClient(context.Context, *ClientProfileReq) (*ClientProfileRes, error)
	BlockUser(context.Context, *BlockReq) (*BlockRes, error)
	UnBlockUser(context.Context, *BlockReq) (*BlockRes, error)
	AddSkill(context.Context, *AddSkillReq) (*AddSkillRes, error)
	AdminLogin(context.Context, *LoginReq) (*LoginRes, error)
	UpdateProfilePhoto(context.Context, *PhotoReq) (*PhotoRes, error)
	OnboardFreelancerToPaypal(context.Context, *OnboardToPaypalReq) (*OnboardToPaypalRes, error)
	ReviewFreelancer(context.Context, *ReviewFlancerReq) (*ReviewFlancerRes, error)
	AddPaymentEmail(context.Context, *AddPaymentEmailReq) (*AddPaymentEmailRes, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (UnimplementedAuthServiceServer) Login(context.Context, *UserLoginReq) (*UserLoginRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) Signup(context.Context, *UserSignupReq) (*UserSignupRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedAuthServiceServer) Verify(context.Context, *VerifyReq) (*VerifyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedAuthServiceServer) ForgotPassword(context.Context, *FPreq) (*FPres, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForgotPassword not implemented")
}
func (UnimplementedAuthServiceServer) ResetPassword(context.Context, *RPreq) (*RPres, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPassword not implemented")
}
func (UnimplementedAuthServiceServer) AddProfileDescription(context.Context, *APDReq) (*APDRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProfileDescription not implemented")
}
func (UnimplementedAuthServiceServer) UpdateProfileDescription(context.Context, *UPDReq) (*UPDRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfileDescription not implemented")
}
func (UnimplementedAuthServiceServer) AddEducation(context.Context, *AddEducationReq) (*AddEducationRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEducation not implemented")
}
func (UnimplementedAuthServiceServer) UpdateEducation(context.Context, *UpdateEducationReq) (*UpdateEducationRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEducation not implemented")
}
func (UnimplementedAuthServiceServer) DeleteEducation(context.Context, *DeleteEducationReq) (*DeleteEducationRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEducation not implemented")
}
func (UnimplementedAuthServiceServer) GetProfile(context.Context, *GetProfileReq) (*GetProfileRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedAuthServiceServer) EditSkill(context.Context, *EditSkillReq) (*EditSkillRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditSkill not implemented")
}
func (UnimplementedAuthServiceServer) AddExperience(context.Context, *ExpReq) (*ExpRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddExperience not implemented")
}
func (UnimplementedAuthServiceServer) UpdateExperience(context.Context, *ExpReq) (*ExpRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateExperience not implemented")
}
func (UnimplementedAuthServiceServer) DeleteExperience(context.Context, *DltExpReq) (*DltExpRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExperience not implemented")
}
func (UnimplementedAuthServiceServer) GetProfileClient(context.Context, *ClientProfileReq) (*ClientProfileRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileClient not implemented")
}
func (UnimplementedAuthServiceServer) BlockUser(context.Context, *BlockReq) (*BlockRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlockUser not implemented")
}
func (UnimplementedAuthServiceServer) UnBlockUser(context.Context, *BlockReq) (*BlockRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnBlockUser not implemented")
}
func (UnimplementedAuthServiceServer) AddSkill(context.Context, *AddSkillReq) (*AddSkillRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSkill not implemented")
}
func (UnimplementedAuthServiceServer) AdminLogin(context.Context, *LoginReq) (*LoginRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminLogin not implemented")
}
func (UnimplementedAuthServiceServer) UpdateProfilePhoto(context.Context, *PhotoReq) (*PhotoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfilePhoto not implemented")
}
func (UnimplementedAuthServiceServer) OnboardFreelancerToPaypal(context.Context, *OnboardToPaypalReq) (*OnboardToPaypalRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnboardFreelancerToPaypal not implemented")
}
func (UnimplementedAuthServiceServer) ReviewFreelancer(context.Context, *ReviewFlancerReq) (*ReviewFlancerRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReviewFreelancer not implemented")
}
func (UnimplementedAuthServiceServer) AddPaymentEmail(context.Context, *AddPaymentEmailReq) (*AddPaymentEmailRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPaymentEmail not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*UserLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSignupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Signup(ctx, req.(*UserSignupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Verify(ctx, req.(*VerifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FPreq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/ForgotPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ForgotPassword(ctx, req.(*FPreq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPreq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ResetPassword(ctx, req.(*RPreq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_AddProfileDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AddProfileDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/AddProfileDescription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AddProfileDescription(ctx, req.(*APDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateProfileDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UPDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateProfileDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/UpdateProfileDescription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateProfileDescription(ctx, req.(*UPDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_AddEducation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEducationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AddEducation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/AddEducation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AddEducation(ctx, req.(*AddEducationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateEducation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEducationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateEducation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/UpdateEducation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateEducation(ctx, req.(*UpdateEducationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DeleteEducation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEducationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DeleteEducation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/DeleteEducation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DeleteEducation(ctx, req.(*DeleteEducationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetProfile(ctx, req.(*GetProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_EditSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditSkillReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).EditSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/EditSkill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).EditSkill(ctx, req.(*EditSkillReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_AddExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AddExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/AddExperience",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AddExperience(ctx, req.(*ExpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/UpdateExperience",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateExperience(ctx, req.(*ExpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DeleteExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DltExpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DeleteExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/DeleteExperience",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DeleteExperience(ctx, req.(*DltExpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetProfileClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetProfileClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/GetProfileClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetProfileClient(ctx, req.(*ClientProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_BlockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).BlockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/BlockUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).BlockUser(ctx, req.(*BlockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UnBlockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UnBlockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/UnBlockUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UnBlockUser(ctx, req.(*BlockReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_AddSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSkillReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AddSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/AddSkill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AddSkill(ctx, req.(*AddSkillReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_AdminLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AdminLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/AdminLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AdminLogin(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateProfilePhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhotoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateProfilePhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/UpdateProfilePhoto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateProfilePhoto(ctx, req.(*PhotoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_OnboardFreelancerToPaypal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnboardToPaypalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).OnboardFreelancerToPaypal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/OnboardFreelancerToPaypal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).OnboardFreelancerToPaypal(ctx, req.(*OnboardToPaypalReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ReviewFreelancer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewFlancerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ReviewFreelancer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/ReviewFreelancer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ReviewFreelancer(ctx, req.(*ReviewFlancerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_AddPaymentEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPaymentEmailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AddPaymentEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/AddPaymentEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AddPaymentEmail(ctx, req.(*AddPaymentEmailReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "Signup",
			Handler:    _AuthService_Signup_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _AuthService_Verify_Handler,
		},
		{
			MethodName: "ForgotPassword",
			Handler:    _AuthService_ForgotPassword_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _AuthService_ResetPassword_Handler,
		},
		{
			MethodName: "AddProfileDescription",
			Handler:    _AuthService_AddProfileDescription_Handler,
		},
		{
			MethodName: "UpdateProfileDescription",
			Handler:    _AuthService_UpdateProfileDescription_Handler,
		},
		{
			MethodName: "AddEducation",
			Handler:    _AuthService_AddEducation_Handler,
		},
		{
			MethodName: "UpdateEducation",
			Handler:    _AuthService_UpdateEducation_Handler,
		},
		{
			MethodName: "DeleteEducation",
			Handler:    _AuthService_DeleteEducation_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _AuthService_GetProfile_Handler,
		},
		{
			MethodName: "EditSkill",
			Handler:    _AuthService_EditSkill_Handler,
		},
		{
			MethodName: "AddExperience",
			Handler:    _AuthService_AddExperience_Handler,
		},
		{
			MethodName: "UpdateExperience",
			Handler:    _AuthService_UpdateExperience_Handler,
		},
		{
			MethodName: "DeleteExperience",
			Handler:    _AuthService_DeleteExperience_Handler,
		},
		{
			MethodName: "GetProfileClient",
			Handler:    _AuthService_GetProfileClient_Handler,
		},
		{
			MethodName: "BlockUser",
			Handler:    _AuthService_BlockUser_Handler,
		},
		{
			MethodName: "UnBlockUser",
			Handler:    _AuthService_UnBlockUser_Handler,
		},
		{
			MethodName: "AddSkill",
			Handler:    _AuthService_AddSkill_Handler,
		},
		{
			MethodName: "AdminLogin",
			Handler:    _AuthService_AdminLogin_Handler,
		},
		{
			MethodName: "UpdateProfilePhoto",
			Handler:    _AuthService_UpdateProfilePhoto_Handler,
		},
		{
			MethodName: "OnboardFreelancerToPaypal",
			Handler:    _AuthService_OnboardFreelancerToPaypal_Handler,
		},
		{
			MethodName: "ReviewFreelancer",
			Handler:    _AuthService_ReviewFreelancer_Handler,
		},
		{
			MethodName: "AddPaymentEmail",
			Handler:    _AuthService_AddPaymentEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/auth/auth.proto",
}
