// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: pb/project/project.proto

package project

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectPaymentRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProjectPaymentRes) Reset() {
	*x = ProjectPaymentRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_project_project_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectPaymentRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectPaymentRes) ProtoMessage() {}

func (x *ProjectPaymentRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_project_project_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectPaymentRes.ProtoReflect.Descriptor instead.
func (*ProjectPaymentRes) Descriptor() ([]byte, []int) {
	return file_pb_project_project_proto_rawDescGZIP(), []int{0}
}

type ProjectPaymentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProjectPaymentReq) Reset() {
	*x = ProjectPaymentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_project_project_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectPaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectPaymentReq) ProtoMessage() {}

func (x *ProjectPaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_project_project_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectPaymentReq.ProtoReflect.Descriptor instead.
func (*ProjectPaymentReq) Descriptor() ([]byte, []int) {
	return file_pb_project_project_proto_rawDescGZIP(), []int{1}
}

type BuyProjectRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error    string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Response string `protobuf:"bytes,3,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *BuyProjectRes) Reset() {
	*x = BuyProjectRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_project_project_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyProjectRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyProjectRes) ProtoMessage() {}

func (x *BuyProjectRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_project_project_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyProjectRes.ProtoReflect.Descriptor instead.
func (*BuyProjectRes) Descriptor() ([]byte, []int) {
	return file_pb_project_project_proto_rawDescGZIP(), []int{2}
}

func (x *BuyProjectRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BuyProjectRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BuyProjectRes) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type BuyProjectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
}

func (x *BuyProjectReq) Reset() {
	*x = BuyProjectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_project_project_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyProjectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyProjectReq) ProtoMessage() {}

func (x *BuyProjectReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_project_project_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyProjectReq.ProtoReflect.Descriptor instead.
func (*BuyProjectReq) Descriptor() ([]byte, []int) {
	return file_pb_project_project_proto_rawDescGZIP(), []int{3}
}

func (x *BuyProjectReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BuyProjectReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListMyProjectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ListMyProjectReq) Reset() {
	*x = ListMyProjectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_project_project_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMyProjectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyProjectReq) ProtoMessage() {}

func (x *ListMyProjectReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_project_project_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyProjectReq.ProtoReflect.Descriptor instead.
func (*ListMyProjectReq) Descriptor() ([]byte, []int) {
	return file_pb_project_project_proto_rawDescGZIP(), []int{4}
}

func (x *ListMyProjectReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListMyProjectRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Project  []*Project `protobuf:"bytes,1,rep,name=Project,proto3" json:"Project,omitempty"`
	Status   int64      `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error    string     `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	Response string     `protobuf:"bytes,4,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *ListMyProjectRes) Reset() {
	*x = ListMyProjectRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_project_project_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMyProjectRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyProjectRes) ProtoMessage() {}

func (x *ListMyProjectRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_project_project_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyProjectRes.ProtoReflect.Descriptor instead.
func (*ListMyProjectRes) Descriptor() ([]byte, []int) {
	return file_pb_project_project_proto_rawDescGZIP(), []int{5}
}

func (x *ListMyProjectRes) GetProject() []*Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *ListMyProjectRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListMyProjectRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListMyProjectRes) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type RemProjectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
}

func (x *RemProjectReq) Reset() {
	*x = RemProjectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_project_project_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemProjectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemProjectReq) ProtoMessage() {}

func (x *RemProjectReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_project_project_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemProjectReq.ProtoReflect.Descriptor instead.
func (*RemProjectReq) Descriptor() ([]byte, []int) {
	return file_pb_project_project_proto_rawDescGZIP(), []int{6}
}

func (x *RemProjectReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemProjectReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type RemProjectRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error    string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Response string `protobuf:"bytes,3,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *RemProjectRes) Reset() {
	*x = RemProjectRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_project_project_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemProjectRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemProjectRes) ProtoMessage() {}

func (x *RemProjectRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_project_project_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemProjectRes.ProtoReflect.Descriptor instead.
func (*RemProjectRes) Descriptor() ([]byte, []int) {
	return file_pb_project_project_proto_rawDescGZIP(), []int{7}
}

func (x *RemProjectRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RemProjectRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RemProjectRes) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type ListOneProjectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
}

func (x *ListOneProjectReq) Reset() {
	*x = ListOneProjectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_project_project_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOneProjectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOneProjectReq) ProtoMessage() {}

func (x *ListOneProjectReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_project_project_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOneProjectReq.ProtoReflect.Descriptor instead.
func (*ListOneProjectReq) Descriptor() ([]byte, []int) {
	return file_pb_project_project_proto_rawDescGZIP(), []int{8}
}

func (x *ListOneProjectReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListOneProjectRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Project  *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Status   int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error    string   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	Response string   `protobuf:"bytes,4,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *ListOneProjectRes) Reset() {
	*x = ListOneProjectRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_project_project_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOneProjectRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOneProjectRes) ProtoMessage() {}

func (x *ListOneProjectRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_project_project_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOneProjectRes.ProtoReflect.Descriptor instead.
func (*ListOneProjectRes) Descriptor() ([]byte, []int) {
	return file_pb_project_project_proto_rawDescGZIP(), []int{9}
}

func (x *ListOneProjectRes) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *ListOneProjectRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListOneProjectRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListOneProjectRes) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type NoParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoParam) Reset() {
	*x = NoParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_project_project_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoParam) ProtoMessage() {}

func (x *NoParam) ProtoReflect() protoreflect.Message {
	mi := &file_pb_project_project_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoParam.ProtoReflect.Descriptor instead.
func (*NoParam) Descriptor() ([]byte, []int) {
	return file_pb_project_project_proto_rawDescGZIP(), []int{10}
}

type Project struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                int32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title             string  `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description       string  `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Category          string  `protobuf:"bytes,4,opt,name=Category,proto3" json:"Category,omitempty"`
	Price             float64 `protobuf:"fixed64,5,opt,name=Price,proto3" json:"Price,omitempty"`
	DeliveryDays      int32   `protobuf:"varint,6,opt,name=delivery_days,json=deliveryDays,proto3" json:"delivery_days,omitempty"`
	NumberOfRevisions int32   `protobuf:"varint,7,opt,name=number_of_revisions,json=numberOfRevisions,proto3" json:"number_of_revisions,omitempty"`
}

func (x *Project) Reset() {
	*x = Project{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_project_project_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_pb_project_project_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_pb_project_project_proto_rawDescGZIP(), []int{11}
}

func (x *Project) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Project) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Project) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Project) GetDeliveryDays() int32 {
	if x != nil {
		return x.DeliveryDays
	}
	return 0
}

func (x *Project) GetNumberOfRevisions() int32 {
	if x != nil {
		return x.NumberOfRevisions
	}
	return 0
}

type ListProjectsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Project  []*Project `protobuf:"bytes,1,rep,name=project,proto3" json:"project,omitempty"`
	Status   int64      `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error    string     `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	Response string     `protobuf:"bytes,4,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *ListProjectsRes) Reset() {
	*x = ListProjectsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_project_project_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListProjectsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRes) ProtoMessage() {}

func (x *ListProjectsRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_project_project_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRes.ProtoReflect.Descriptor instead.
func (*ListProjectsRes) Descriptor() ([]byte, []int) {
	return file_pb_project_project_proto_rawDescGZIP(), []int{12}
}

func (x *ListProjectsRes) GetProject() []*Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *ListProjectsRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListProjectsRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListProjectsRes) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type EditSingleProjectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title             string  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description       string  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category          int32   `protobuf:"varint,3,opt,name=category,proto3" json:"category,omitempty"`
	Type              string  `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Price             float64 `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	DeliveryDays      int64   `protobuf:"varint,6,opt,name=delivery_days,json=deliveryDays,proto3" json:"delivery_days,omitempty"`
	NumberOfRevisions int64   `protobuf:"varint,7,opt,name=number_of_revisions,json=numberOfRevisions,proto3" json:"number_of_revisions,omitempty"`
	UserId            string  `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId         string  `protobuf:"bytes,9,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
}

func (x *EditSingleProjectReq) Reset() {
	*x = EditSingleProjectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_project_project_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditSingleProjectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditSingleProjectReq) ProtoMessage() {}

func (x *EditSingleProjectReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_project_project_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditSingleProjectReq.ProtoReflect.Descriptor instead.
func (*EditSingleProjectReq) Descriptor() ([]byte, []int) {
	return file_pb_project_project_proto_rawDescGZIP(), []int{13}
}

func (x *EditSingleProjectReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EditSingleProjectReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EditSingleProjectReq) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *EditSingleProjectReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EditSingleProjectReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *EditSingleProjectReq) GetDeliveryDays() int64 {
	if x != nil {
		return x.DeliveryDays
	}
	return 0
}

func (x *EditSingleProjectReq) GetNumberOfRevisions() int64 {
	if x != nil {
		return x.NumberOfRevisions
	}
	return 0
}

func (x *EditSingleProjectReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EditSingleProjectReq) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type EditSingleProjectRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error    string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Response string `protobuf:"bytes,3,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *EditSingleProjectRes) Reset() {
	*x = EditSingleProjectRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_project_project_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditSingleProjectRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditSingleProjectRes) ProtoMessage() {}

func (x *EditSingleProjectRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_project_project_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditSingleProjectRes.ProtoReflect.Descriptor instead.
func (*EditSingleProjectRes) Descriptor() ([]byte, []int) {
	return file_pb_project_project_proto_rawDescGZIP(), []int{14}
}

func (x *EditSingleProjectRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EditSingleProjectRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EditSingleProjectRes) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type AddSingleProjectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title             string  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description       string  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category          int32   `protobuf:"varint,3,opt,name=category,proto3" json:"category,omitempty"`
	Type              string  `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Price             float64 `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	DeliveryDays      int64   `protobuf:"varint,6,opt,name=delivery_days,json=deliveryDays,proto3" json:"delivery_days,omitempty"`
	NumberOfRevisions int64   `protobuf:"varint,7,opt,name=number_of_revisions,json=numberOfRevisions,proto3" json:"number_of_revisions,omitempty"`
	UserId            string  `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *AddSingleProjectReq) Reset() {
	*x = AddSingleProjectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_project_project_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSingleProjectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSingleProjectReq) ProtoMessage() {}

func (x *AddSingleProjectReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_project_project_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSingleProjectReq.ProtoReflect.Descriptor instead.
func (*AddSingleProjectReq) Descriptor() ([]byte, []int) {
	return file_pb_project_project_proto_rawDescGZIP(), []int{15}
}

func (x *AddSingleProjectReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddSingleProjectReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddSingleProjectReq) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *AddSingleProjectReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddSingleProjectReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddSingleProjectReq) GetDeliveryDays() int64 {
	if x != nil {
		return x.DeliveryDays
	}
	return 0
}

func (x *AddSingleProjectReq) GetNumberOfRevisions() int64 {
	if x != nil {
		return x.NumberOfRevisions
	}
	return 0
}

func (x *AddSingleProjectReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CustomTier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title             string  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description       string  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DeliveryDays      int64   `protobuf:"varint,3,opt,name=delivery_days,json=deliveryDays,proto3" json:"delivery_days,omitempty"`
	NumberOfRevisions int64   `protobuf:"varint,4,opt,name=number_of_revisions,json=numberOfRevisions,proto3" json:"number_of_revisions,omitempty"`
	Price             float64 `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *CustomTier) Reset() {
	*x = CustomTier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_project_project_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomTier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomTier) ProtoMessage() {}

func (x *CustomTier) ProtoReflect() protoreflect.Message {
	mi := &file_pb_project_project_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomTier.ProtoReflect.Descriptor instead.
func (*CustomTier) Descriptor() ([]byte, []int) {
	return file_pb_project_project_proto_rawDescGZIP(), []int{16}
}

func (x *CustomTier) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CustomTier) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CustomTier) GetDeliveryDays() int64 {
	if x != nil {
		return x.DeliveryDays
	}
	return 0
}

func (x *CustomTier) GetNumberOfRevisions() int64 {
	if x != nil {
		return x.NumberOfRevisions
	}
	return 0
}

func (x *CustomTier) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type AddSingleProjectRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error    string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Response string `protobuf:"bytes,3,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *AddSingleProjectRes) Reset() {
	*x = AddSingleProjectRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_project_project_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSingleProjectRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSingleProjectRes) ProtoMessage() {}

func (x *AddSingleProjectRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_project_project_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSingleProjectRes.ProtoReflect.Descriptor instead.
func (*AddSingleProjectRes) Descriptor() ([]byte, []int) {
	return file_pb_project_project_proto_rawDescGZIP(), []int{17}
}

func (x *AddSingleProjectRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddSingleProjectRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AddSingleProjectRes) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_pb_project_project_proto protoreflect.FileDescriptor

var file_pb_project_project_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x22, 0x59, 0x0a,
	0x0d, 0x42, 0x75, 0x79, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x47, 0x0a, 0x0d, 0x42, 0x75, 0x79, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x22, 0x2b, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x79, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x88,
	0x01, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x79, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x47, 0x0a, 0x0d, 0x52, 0x65, 0x6d,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x49, 0x64, 0x22, 0x59, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x32, 0x0a,
	0x11, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x22, 0x89, 0x01, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x09, 0x0a,
	0x07, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x22, 0xd8, 0x01, 0x0a, 0x07, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x44,
	0x61, 0x79, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66,
	0x5f, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x11, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0x87, 0x01, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xa1, 0x02,
	0x0a, 0x14, 0x45, 0x64, 0x69, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x64, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x79, 0x44, 0x61, 0x79, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66,
	0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x22, 0x60, 0x0a, 0x14, 0x45, 0x64, 0x69, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x81, 0x02, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x44, 0x61, 0x79, 0x73, 0x12, 0x2e,
	0x0a, 0x13, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x72, 0x65, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x4f, 0x66, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xaf, 0x01, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x54, 0x69, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23,
	0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x44,
	0x61, 0x79, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66,
	0x5f, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x11, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x5f, 0x0a, 0x13, 0x41, 0x64, 0x64,
	0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xd1, 0x04, 0x0a, 0x0e, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a,
	0x0a, 0x41, 0x64, 0x64, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0b, 0x45, 0x64, 0x69,
	0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0c, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x10, 0x2e, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0e, 0x4c, 0x69, 0x73,
	0x74, 0x4f, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x79, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x79, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x4d, 0x79, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x3e, 0x0a, 0x0a, 0x42, 0x75, 0x79, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x16, 0x2e,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x42, 0x75, 0x79, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e,
	0x42, 0x75, 0x79, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x4d, 0x0a, 0x11, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x6f, 0x72, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0e,
	0x5a, 0x0c, 0x2e, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_project_project_proto_rawDescOnce sync.Once
	file_pb_project_project_proto_rawDescData = file_pb_project_project_proto_rawDesc
)

func file_pb_project_project_proto_rawDescGZIP() []byte {
	file_pb_project_project_proto_rawDescOnce.Do(func() {
		file_pb_project_project_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_project_project_proto_rawDescData)
	})
	return file_pb_project_project_proto_rawDescData
}

var file_pb_project_project_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pb_project_project_proto_goTypes = []interface{}{
	(*ProjectPaymentRes)(nil),    // 0: project.ProjectPaymentRes
	(*ProjectPaymentReq)(nil),    // 1: project.ProjectPaymentReq
	(*BuyProjectRes)(nil),        // 2: project.BuyProjectRes
	(*BuyProjectReq)(nil),        // 3: project.BuyProjectReq
	(*ListMyProjectReq)(nil),     // 4: project.ListMyProjectReq
	(*ListMyProjectRes)(nil),     // 5: project.ListMyProjectRes
	(*RemProjectReq)(nil),        // 6: project.RemProjectReq
	(*RemProjectRes)(nil),        // 7: project.RemProjectRes
	(*ListOneProjectReq)(nil),    // 8: project.ListOneProjectReq
	(*ListOneProjectRes)(nil),    // 9: project.ListOneProjectRes
	(*NoParam)(nil),              // 10: project.NoParam
	(*Project)(nil),              // 11: project.Project
	(*ListProjectsRes)(nil),      // 12: project.ListProjectsRes
	(*EditSingleProjectReq)(nil), // 13: project.EditSingleProjectReq
	(*EditSingleProjectRes)(nil), // 14: project.EditSingleProjectRes
	(*AddSingleProjectReq)(nil),  // 15: project.AddSingleProjectReq
	(*CustomTier)(nil),           // 16: project.CustomTier
	(*AddSingleProjectRes)(nil),  // 17: project.AddSingleProjectRes
}
var file_pb_project_project_proto_depIdxs = []int32{
	11, // 0: project.ListMyProjectRes.Project:type_name -> project.Project
	11, // 1: project.ListOneProjectRes.project:type_name -> project.Project
	11, // 2: project.ListProjectsRes.project:type_name -> project.Project
	15, // 3: project.ProjectService.AddProject:input_type -> project.AddSingleProjectReq
	13, // 4: project.ProjectService.EditProject:input_type -> project.EditSingleProjectReq
	6,  // 5: project.ProjectService.RemoveProject:input_type -> project.RemProjectReq
	10, // 6: project.ProjectService.ListProjects:input_type -> project.NoParam
	8,  // 7: project.ProjectService.ListOneProject:input_type -> project.ListOneProjectReq
	4,  // 8: project.ProjectService.ListMyProjects:input_type -> project.ListMyProjectReq
	3,  // 9: project.ProjectService.BuyProject:input_type -> project.BuyProjectReq
	1,  // 10: project.ProjectService.PaymentForProject:input_type -> project.ProjectPaymentReq
	17, // 11: project.ProjectService.AddProject:output_type -> project.AddSingleProjectRes
	14, // 12: project.ProjectService.EditProject:output_type -> project.EditSingleProjectRes
	7,  // 13: project.ProjectService.RemoveProject:output_type -> project.RemProjectRes
	12, // 14: project.ProjectService.ListProjects:output_type -> project.ListProjectsRes
	9,  // 15: project.ProjectService.ListOneProject:output_type -> project.ListOneProjectRes
	5,  // 16: project.ProjectService.ListMyProjects:output_type -> project.ListMyProjectRes
	2,  // 17: project.ProjectService.BuyProject:output_type -> project.BuyProjectRes
	0,  // 18: project.ProjectService.PaymentForProject:output_type -> project.ProjectPaymentRes
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pb_project_project_proto_init() }
func file_pb_project_project_proto_init() {
	if File_pb_project_project_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_project_project_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectPaymentRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_project_project_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectPaymentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_project_project_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyProjectRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_project_project_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyProjectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_project_project_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMyProjectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_project_project_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMyProjectRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_project_project_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemProjectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_project_project_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemProjectRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_project_project_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOneProjectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_project_project_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOneProjectRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_project_project_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_project_project_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Project); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_project_project_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListProjectsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_project_project_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditSingleProjectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_project_project_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditSingleProjectRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_project_project_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSingleProjectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_project_project_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomTier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_project_project_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSingleProjectRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_project_project_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_project_project_proto_goTypes,
		DependencyIndexes: file_pb_project_project_proto_depIdxs,
		MessageInfos:      file_pb_project_project_proto_msgTypes,
	}.Build()
	File_pb_project_project_proto = out.File
	file_pb_project_project_proto_rawDesc = nil
	file_pb_project_project_proto_goTypes = nil
	file_pb_project_project_proto_depIdxs = nil
}
