// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: pb/project/project.proto

package project

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectServiceClient interface {
	AddProject(ctx context.Context, in *AddSingleProjectReq, opts ...grpc.CallOption) (*AddSingleProjectRes, error)
	EditProject(ctx context.Context, in *EditSingleProjectReq, opts ...grpc.CallOption) (*EditSingleProjectRes, error)
	RemoveProject(ctx context.Context, in *RemProjectReq, opts ...grpc.CallOption) (*RemProjectRes, error)
	ListProjects(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*ListProjectsRes, error)
	ListOneProject(ctx context.Context, in *ListOneProjectReq, opts ...grpc.CallOption) (*ListOneProjectRes, error)
	ListMyProjects(ctx context.Context, in *ListMyProjectReq, opts ...grpc.CallOption) (*ListMyProjectRes, error)
	OrderProject(ctx context.Context, in *BuyProjectReq, opts ...grpc.CallOption) (*BuyProjectRes, error)
	ExecutePaymentProject(ctx context.Context, in *ExecutePaymentReq, opts ...grpc.CallOption) (*ExecutePaymentRes, error)
	CapturePaymentProject(ctx context.Context, in *CapturePaymentReq, opts ...grpc.CallOption) (*CapturePaymentRes, error)
	GetProjectOrdersForClient(ctx context.Context, in *GetOrdersReq, opts ...grpc.CallOption) (*GetOrdersClientRes, error)
	GetProjectOrdersForFreelancer(ctx context.Context, in *GetOrdersReq, opts ...grpc.CallOption) (*GetOrdersFreelancerRes, error)
}

type projectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectServiceClient(cc grpc.ClientConnInterface) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) AddProject(ctx context.Context, in *AddSingleProjectReq, opts ...grpc.CallOption) (*AddSingleProjectRes, error) {
	out := new(AddSingleProjectRes)
	err := c.cc.Invoke(ctx, "/project.ProjectService/AddProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) EditProject(ctx context.Context, in *EditSingleProjectReq, opts ...grpc.CallOption) (*EditSingleProjectRes, error) {
	out := new(EditSingleProjectRes)
	err := c.cc.Invoke(ctx, "/project.ProjectService/EditProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) RemoveProject(ctx context.Context, in *RemProjectReq, opts ...grpc.CallOption) (*RemProjectRes, error) {
	out := new(RemProjectRes)
	err := c.cc.Invoke(ctx, "/project.ProjectService/RemoveProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) ListProjects(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*ListProjectsRes, error) {
	out := new(ListProjectsRes)
	err := c.cc.Invoke(ctx, "/project.ProjectService/ListProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) ListOneProject(ctx context.Context, in *ListOneProjectReq, opts ...grpc.CallOption) (*ListOneProjectRes, error) {
	out := new(ListOneProjectRes)
	err := c.cc.Invoke(ctx, "/project.ProjectService/ListOneProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) ListMyProjects(ctx context.Context, in *ListMyProjectReq, opts ...grpc.CallOption) (*ListMyProjectRes, error) {
	out := new(ListMyProjectRes)
	err := c.cc.Invoke(ctx, "/project.ProjectService/ListMyProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) OrderProject(ctx context.Context, in *BuyProjectReq, opts ...grpc.CallOption) (*BuyProjectRes, error) {
	out := new(BuyProjectRes)
	err := c.cc.Invoke(ctx, "/project.ProjectService/OrderProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) ExecutePaymentProject(ctx context.Context, in *ExecutePaymentReq, opts ...grpc.CallOption) (*ExecutePaymentRes, error) {
	out := new(ExecutePaymentRes)
	err := c.cc.Invoke(ctx, "/project.ProjectService/ExecutePaymentProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) CapturePaymentProject(ctx context.Context, in *CapturePaymentReq, opts ...grpc.CallOption) (*CapturePaymentRes, error) {
	out := new(CapturePaymentRes)
	err := c.cc.Invoke(ctx, "/project.ProjectService/CapturePaymentProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectOrdersForClient(ctx context.Context, in *GetOrdersReq, opts ...grpc.CallOption) (*GetOrdersClientRes, error) {
	out := new(GetOrdersClientRes)
	err := c.cc.Invoke(ctx, "/project.ProjectService/GetProjectOrdersForClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectOrdersForFreelancer(ctx context.Context, in *GetOrdersReq, opts ...grpc.CallOption) (*GetOrdersFreelancerRes, error) {
	out := new(GetOrdersFreelancerRes)
	err := c.cc.Invoke(ctx, "/project.ProjectService/GetProjectOrdersForFreelancer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceServer is the server API for ProjectService service.
// All implementations must embed UnimplementedProjectServiceServer
// for forward compatibility
type ProjectServiceServer interface {
	AddProject(context.Context, *AddSingleProjectReq) (*AddSingleProjectRes, error)
	EditProject(context.Context, *EditSingleProjectReq) (*EditSingleProjectRes, error)
	RemoveProject(context.Context, *RemProjectReq) (*RemProjectRes, error)
	ListProjects(context.Context, *NoParam) (*ListProjectsRes, error)
	ListOneProject(context.Context, *ListOneProjectReq) (*ListOneProjectRes, error)
	ListMyProjects(context.Context, *ListMyProjectReq) (*ListMyProjectRes, error)
	OrderProject(context.Context, *BuyProjectReq) (*BuyProjectRes, error)
	ExecutePaymentProject(context.Context, *ExecutePaymentReq) (*ExecutePaymentRes, error)
	CapturePaymentProject(context.Context, *CapturePaymentReq) (*CapturePaymentRes, error)
	GetProjectOrdersForClient(context.Context, *GetOrdersReq) (*GetOrdersClientRes, error)
	GetProjectOrdersForFreelancer(context.Context, *GetOrdersReq) (*GetOrdersFreelancerRes, error)
	mustEmbedUnimplementedProjectServiceServer()
}

// UnimplementedProjectServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProjectServiceServer struct {
}

func (UnimplementedProjectServiceServer) AddProject(context.Context, *AddSingleProjectReq) (*AddSingleProjectRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProject not implemented")
}
func (UnimplementedProjectServiceServer) EditProject(context.Context, *EditSingleProjectReq) (*EditSingleProjectRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditProject not implemented")
}
func (UnimplementedProjectServiceServer) RemoveProject(context.Context, *RemProjectReq) (*RemProjectRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveProject not implemented")
}
func (UnimplementedProjectServiceServer) ListProjects(context.Context, *NoParam) (*ListProjectsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedProjectServiceServer) ListOneProject(context.Context, *ListOneProjectReq) (*ListOneProjectRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOneProject not implemented")
}
func (UnimplementedProjectServiceServer) ListMyProjects(context.Context, *ListMyProjectReq) (*ListMyProjectRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyProjects not implemented")
}
func (UnimplementedProjectServiceServer) OrderProject(context.Context, *BuyProjectReq) (*BuyProjectRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderProject not implemented")
}
func (UnimplementedProjectServiceServer) ExecutePaymentProject(context.Context, *ExecutePaymentReq) (*ExecutePaymentRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecutePaymentProject not implemented")
}
func (UnimplementedProjectServiceServer) CapturePaymentProject(context.Context, *CapturePaymentReq) (*CapturePaymentRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CapturePaymentProject not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectOrdersForClient(context.Context, *GetOrdersReq) (*GetOrdersClientRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectOrdersForClient not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectOrdersForFreelancer(context.Context, *GetOrdersReq) (*GetOrdersFreelancerRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectOrdersForFreelancer not implemented")
}
func (UnimplementedProjectServiceServer) mustEmbedUnimplementedProjectServiceServer() {}

// UnsafeProjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectServiceServer will
// result in compilation errors.
type UnsafeProjectServiceServer interface {
	mustEmbedUnimplementedProjectServiceServer()
}

func RegisterProjectServiceServer(s grpc.ServiceRegistrar, srv ProjectServiceServer) {
	s.RegisterService(&ProjectService_ServiceDesc, srv)
}

func _ProjectService_AddProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSingleProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).AddProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.ProjectService/AddProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).AddProject(ctx, req.(*AddSingleProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_EditProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditSingleProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).EditProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.ProjectService/EditProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).EditProject(ctx, req.(*EditSingleProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_RemoveProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).RemoveProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.ProjectService/RemoveProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).RemoveProject(ctx, req.(*RemProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.ProjectService/ListProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ListProjects(ctx, req.(*NoParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_ListOneProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOneProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ListOneProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.ProjectService/ListOneProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ListOneProject(ctx, req.(*ListOneProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_ListMyProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ListMyProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.ProjectService/ListMyProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ListMyProjects(ctx, req.(*ListMyProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_OrderProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).OrderProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.ProjectService/OrderProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).OrderProject(ctx, req.(*BuyProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_ExecutePaymentProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutePaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ExecutePaymentProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.ProjectService/ExecutePaymentProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ExecutePaymentProject(ctx, req.(*ExecutePaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_CapturePaymentProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapturePaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).CapturePaymentProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.ProjectService/CapturePaymentProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).CapturePaymentProject(ctx, req.(*CapturePaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectOrdersForClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectOrdersForClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.ProjectService/GetProjectOrdersForClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectOrdersForClient(ctx, req.(*GetOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectOrdersForFreelancer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectOrdersForFreelancer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.ProjectService/GetProjectOrdersForFreelancer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectOrdersForFreelancer(ctx, req.(*GetOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectService_ServiceDesc is the grpc.ServiceDesc for ProjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "project.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProject",
			Handler:    _ProjectService_AddProject_Handler,
		},
		{
			MethodName: "EditProject",
			Handler:    _ProjectService_EditProject_Handler,
		},
		{
			MethodName: "RemoveProject",
			Handler:    _ProjectService_RemoveProject_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _ProjectService_ListProjects_Handler,
		},
		{
			MethodName: "ListOneProject",
			Handler:    _ProjectService_ListOneProject_Handler,
		},
		{
			MethodName: "ListMyProjects",
			Handler:    _ProjectService_ListMyProjects_Handler,
		},
		{
			MethodName: "OrderProject",
			Handler:    _ProjectService_OrderProject_Handler,
		},
		{
			MethodName: "ExecutePaymentProject",
			Handler:    _ProjectService_ExecutePaymentProject_Handler,
		},
		{
			MethodName: "CapturePaymentProject",
			Handler:    _ProjectService_CapturePaymentProject_Handler,
		},
		{
			MethodName: "GetProjectOrdersForClient",
			Handler:    _ProjectService_GetProjectOrdersForClient_Handler,
		},
		{
			MethodName: "GetProjectOrdersForFreelancer",
			Handler:    _ProjectService_GetProjectOrdersForFreelancer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/project/project.proto",
}
