// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: pb/Job/job.proto

package Job

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostjobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title           string  `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Description     string  `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Category        int64   `protobuf:"varint,3,opt,name=category,proto3" json:"category,omitempty"`
	Skills          []int64 `protobuf:"varint,4,rep,packed,name=skills,proto3" json:"skills,omitempty"`
	TimePeriod      string  `protobuf:"bytes,5,opt,name=timePeriod,proto3" json:"timePeriod,omitempty"`
	FreelancerLevel string  `protobuf:"bytes,6,opt,name=freelancerLevel,proto3" json:"freelancerLevel,omitempty"`
	Budget          string  `protobuf:"bytes,7,opt,name=budget,proto3" json:"budget,omitempty"`
	UserId          int64   `protobuf:"varint,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *PostjobReq) Reset() {
	*x = PostjobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_Job_job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostjobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostjobReq) ProtoMessage() {}

func (x *PostjobReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_Job_job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostjobReq.ProtoReflect.Descriptor instead.
func (*PostjobReq) Descriptor() ([]byte, []int) {
	return file_pb_Job_job_proto_rawDescGZIP(), []int{0}
}

func (x *PostjobReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostjobReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PostjobReq) GetCategory() int64 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *PostjobReq) GetSkills() []int64 {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *PostjobReq) GetTimePeriod() string {
	if x != nil {
		return x.TimePeriod
	}
	return ""
}

func (x *PostjobReq) GetFreelancerLevel() string {
	if x != nil {
		return x.FreelancerLevel
	}
	return ""
}

func (x *PostjobReq) GetBudget() string {
	if x != nil {
		return x.Budget
	}
	return ""
}

func (x *PostjobReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PostjobRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error    string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Response string `protobuf:"bytes,3,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *PostjobRes) Reset() {
	*x = PostjobRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_Job_job_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostjobRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostjobRes) ProtoMessage() {}

func (x *PostjobRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_Job_job_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostjobRes.ProtoReflect.Descriptor instead.
func (*PostjobRes) Descriptor() ([]byte, []int) {
	return file_pb_Job_job_proto_rawDescGZIP(), []int{1}
}

func (x *PostjobRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PostjobRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PostjobRes) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type ProposalReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Budget      string   `protobuf:"bytes,1,opt,name=Budget,proto3" json:"Budget,omitempty"`
	CoverLetter string   `protobuf:"bytes,2,opt,name=coverLetter,proto3" json:"coverLetter,omitempty"`
	Attachments [][]byte `protobuf:"bytes,3,rep,name=attachments,proto3" json:"attachments,omitempty"`
	UserId      string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JobId       string   `protobuf:"bytes,5,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *ProposalReq) Reset() {
	*x = ProposalReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_Job_job_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalReq) ProtoMessage() {}

func (x *ProposalReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_Job_job_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalReq.ProtoReflect.Descriptor instead.
func (*ProposalReq) Descriptor() ([]byte, []int) {
	return file_pb_Job_job_proto_rawDescGZIP(), []int{2}
}

func (x *ProposalReq) GetBudget() string {
	if x != nil {
		return x.Budget
	}
	return ""
}

func (x *ProposalReq) GetCoverLetter() string {
	if x != nil {
		return x.CoverLetter
	}
	return ""
}

func (x *ProposalReq) GetAttachments() [][]byte {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *ProposalReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProposalReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ProposalRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error    string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Response string `protobuf:"bytes,3,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *ProposalRes) Reset() {
	*x = ProposalRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_Job_job_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposalRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalRes) ProtoMessage() {}

func (x *ProposalRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_Job_job_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalRes.ProtoReflect.Descriptor instead.
func (*ProposalRes) Descriptor() ([]byte, []int) {
	return file_pb_Job_job_proto_rawDescGZIP(), []int{3}
}

func (x *ProposalRes) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProposalRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ProposalRes) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type SendOfferReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendOfferReq) Reset() {
	*x = SendOfferReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_Job_job_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendOfferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOfferReq) ProtoMessage() {}

func (x *SendOfferReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_Job_job_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOfferReq.ProtoReflect.Descriptor instead.
func (*SendOfferReq) Descriptor() ([]byte, []int) {
	return file_pb_Job_job_proto_rawDescGZIP(), []int{4}
}

type SendOfferRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendOfferRes) Reset() {
	*x = SendOfferRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_Job_job_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendOfferRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOfferRes) ProtoMessage() {}

func (x *SendOfferRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_Job_job_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOfferRes.ProtoReflect.Descriptor instead.
func (*SendOfferRes) Descriptor() ([]byte, []int) {
	return file_pb_Job_job_proto_rawDescGZIP(), []int{5}
}

type AcceptOfferReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AcceptOfferReq) Reset() {
	*x = AcceptOfferReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_Job_job_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptOfferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOfferReq) ProtoMessage() {}

func (x *AcceptOfferReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_Job_job_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOfferReq.ProtoReflect.Descriptor instead.
func (*AcceptOfferReq) Descriptor() ([]byte, []int) {
	return file_pb_Job_job_proto_rawDescGZIP(), []int{6}
}

type AcceptOfferRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AcceptOfferRes) Reset() {
	*x = AcceptOfferRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_Job_job_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptOfferRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOfferRes) ProtoMessage() {}

func (x *AcceptOfferRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_Job_job_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOfferRes.ProtoReflect.Descriptor instead.
func (*AcceptOfferRes) Descriptor() ([]byte, []int) {
	return file_pb_Job_job_proto_rawDescGZIP(), []int{7}
}

type ContractReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ContractReq) Reset() {
	*x = ContractReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_Job_job_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractReq) ProtoMessage() {}

func (x *ContractReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_Job_job_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractReq.ProtoReflect.Descriptor instead.
func (*ContractReq) Descriptor() ([]byte, []int) {
	return file_pb_Job_job_proto_rawDescGZIP(), []int{8}
}

type ViewContractRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ViewContractRes) Reset() {
	*x = ViewContractRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_Job_job_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewContractRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewContractRes) ProtoMessage() {}

func (x *ViewContractRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_Job_job_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewContractRes.ProtoReflect.Descriptor instead.
func (*ViewContractRes) Descriptor() ([]byte, []int) {
	return file_pb_Job_job_proto_rawDescGZIP(), []int{9}
}

var File_pb_Job_job_proto protoreflect.FileDescriptor

var file_pb_Job_job_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x4a, 0x6f, 0x62, 0x2f, 0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x6a, 0x6f, 0x62, 0x22, 0xf3, 0x01, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x74,
	0x6a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6b,
	0x69, 0x6c, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x50, 0x65, 0x72, 0x69,
	0x6f, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x66, 0x72, 0x65, 0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x66, 0x72, 0x65,
	0x65, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75,
	0x64, 0x67, 0x65, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x56, 0x0a,
	0x0a, 0x70, 0x6f, 0x73, 0x74, 0x6a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x99, 0x01, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x12,
	0x20, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f,
	0x62, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49,
	0x64, 0x22, 0x57, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x65,
	0x6e, 0x64, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x65,
	0x6e, 0x64, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x41, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x10, 0x0a, 0x0e,
	0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x0d,
	0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x22, 0x11, 0x0a,
	0x0f, 0x56, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x32, 0x9b, 0x02, 0x0a, 0x0a, 0x4a, 0x6f, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x2d, 0x0a, 0x07, 0x50, 0x6f, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x12, 0x0f, 0x2e, 0x6a, 0x6f, 0x62,
	0x2e, 0x70, 0x6f, 0x73, 0x74, 0x6a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x6a, 0x6f,
	0x62, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x6a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x34,
	0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x12, 0x10,
	0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x1a, 0x10, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x66, 0x66, 0x65,
	0x72, 0x12, 0x11, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x66, 0x66, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4f,
	0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0b, 0x41, 0x63, 0x63,
	0x65, 0x70, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x41,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e,
	0x6a, 0x6f, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0c, 0x56, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x12, 0x10, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x56, 0x69, 0x65,
	0x77, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0b,
	0x5a, 0x09, 0x2e, 0x2f, 0x70, 0x62, 0x2f, 0x4a, 0x6f, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pb_Job_job_proto_rawDescOnce sync.Once
	file_pb_Job_job_proto_rawDescData = file_pb_Job_job_proto_rawDesc
)

func file_pb_Job_job_proto_rawDescGZIP() []byte {
	file_pb_Job_job_proto_rawDescOnce.Do(func() {
		file_pb_Job_job_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_Job_job_proto_rawDescData)
	})
	return file_pb_Job_job_proto_rawDescData
}

var file_pb_Job_job_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pb_Job_job_proto_goTypes = []interface{}{
	(*PostjobReq)(nil),      // 0: job.postjobReq
	(*PostjobRes)(nil),      // 1: job.postjobRes
	(*ProposalReq)(nil),     // 2: job.ProposalReq
	(*ProposalRes)(nil),     // 3: job.ProposalRes
	(*SendOfferReq)(nil),    // 4: job.SendOfferReq
	(*SendOfferRes)(nil),    // 5: job.SendOfferRes
	(*AcceptOfferReq)(nil),  // 6: job.AcceptOfferReq
	(*AcceptOfferRes)(nil),  // 7: job.AcceptOfferRes
	(*ContractReq)(nil),     // 8: job.ContractReq
	(*ViewContractRes)(nil), // 9: job.ViewContractRes
}
var file_pb_Job_job_proto_depIdxs = []int32{
	0, // 0: job.JobService.PostJob:input_type -> job.postjobReq
	2, // 1: job.JobService.SendProposal:input_type -> job.ProposalReq
	4, // 2: job.JobService.SendOffer:input_type -> job.SendOfferReq
	6, // 3: job.JobService.AcceptOffer:input_type -> job.AcceptOfferReq
	8, // 4: job.JobService.ViewContract:input_type -> job.ContractReq
	1, // 5: job.JobService.PostJob:output_type -> job.postjobRes
	3, // 6: job.JobService.SendProposal:output_type -> job.ProposalRes
	5, // 7: job.JobService.SendOffer:output_type -> job.SendOfferRes
	7, // 8: job.JobService.AcceptOffer:output_type -> job.AcceptOfferRes
	9, // 9: job.JobService.ViewContract:output_type -> job.ViewContractRes
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_Job_job_proto_init() }
func file_pb_Job_job_proto_init() {
	if File_pb_Job_job_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_Job_job_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostjobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_Job_job_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostjobRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_Job_job_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposalReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_Job_job_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposalRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_Job_job_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendOfferReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_Job_job_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendOfferRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_Job_job_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptOfferReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_Job_job_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptOfferRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_Job_job_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_Job_job_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewContractRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_Job_job_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_Job_job_proto_goTypes,
		DependencyIndexes: file_pb_Job_job_proto_depIdxs,
		MessageInfos:      file_pb_Job_job_proto_msgTypes,
	}.Build()
	File_pb_Job_job_proto = out.File
	file_pb_Job_job_proto_rawDesc = nil
	file_pb_Job_job_proto_goTypes = nil
	file_pb_Job_job_proto_depIdxs = nil
}
