// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: pb/Job/job.proto

package Job

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JobServiceClient is the client API for JobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobServiceClient interface {
	PostJob(ctx context.Context, in *PostjobReq, opts ...grpc.CallOption) (*PostjobRes, error)
	SendProposal(ctx context.Context, in *ProposalReq, opts ...grpc.CallOption) (*ProposalRes, error)
	SendOffer(ctx context.Context, in *SendOfferReq, opts ...grpc.CallOption) (*SendOfferRes, error)
	AcceptOffer(ctx context.Context, in *AcceptOfferReq, opts ...grpc.CallOption) (*AcceptOfferRes, error)
	ViewContract(ctx context.Context, in *ContractReq, opts ...grpc.CallOption) (*ViewContractRes, error)
}

type jobServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobServiceClient(cc grpc.ClientConnInterface) JobServiceClient {
	return &jobServiceClient{cc}
}

func (c *jobServiceClient) PostJob(ctx context.Context, in *PostjobReq, opts ...grpc.CallOption) (*PostjobRes, error) {
	out := new(PostjobRes)
	err := c.cc.Invoke(ctx, "/job.JobService/PostJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) SendProposal(ctx context.Context, in *ProposalReq, opts ...grpc.CallOption) (*ProposalRes, error) {
	out := new(ProposalRes)
	err := c.cc.Invoke(ctx, "/job.JobService/SendProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) SendOffer(ctx context.Context, in *SendOfferReq, opts ...grpc.CallOption) (*SendOfferRes, error) {
	out := new(SendOfferRes)
	err := c.cc.Invoke(ctx, "/job.JobService/SendOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) AcceptOffer(ctx context.Context, in *AcceptOfferReq, opts ...grpc.CallOption) (*AcceptOfferRes, error) {
	out := new(AcceptOfferRes)
	err := c.cc.Invoke(ctx, "/job.JobService/AcceptOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) ViewContract(ctx context.Context, in *ContractReq, opts ...grpc.CallOption) (*ViewContractRes, error) {
	out := new(ViewContractRes)
	err := c.cc.Invoke(ctx, "/job.JobService/ViewContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServiceServer is the server API for JobService service.
// All implementations must embed UnimplementedJobServiceServer
// for forward compatibility
type JobServiceServer interface {
	PostJob(context.Context, *PostjobReq) (*PostjobRes, error)
	SendProposal(context.Context, *ProposalReq) (*ProposalRes, error)
	SendOffer(context.Context, *SendOfferReq) (*SendOfferRes, error)
	AcceptOffer(context.Context, *AcceptOfferReq) (*AcceptOfferRes, error)
	ViewContract(context.Context, *ContractReq) (*ViewContractRes, error)
	mustEmbedUnimplementedJobServiceServer()
}

// UnimplementedJobServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJobServiceServer struct {
}

func (UnimplementedJobServiceServer) PostJob(context.Context, *PostjobReq) (*PostjobRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostJob not implemented")
}
func (UnimplementedJobServiceServer) SendProposal(context.Context, *ProposalReq) (*ProposalRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendProposal not implemented")
}
func (UnimplementedJobServiceServer) SendOffer(context.Context, *SendOfferReq) (*SendOfferRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOffer not implemented")
}
func (UnimplementedJobServiceServer) AcceptOffer(context.Context, *AcceptOfferReq) (*AcceptOfferRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptOffer not implemented")
}
func (UnimplementedJobServiceServer) ViewContract(context.Context, *ContractReq) (*ViewContractRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewContract not implemented")
}
func (UnimplementedJobServiceServer) mustEmbedUnimplementedJobServiceServer() {}

// UnsafeJobServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobServiceServer will
// result in compilation errors.
type UnsafeJobServiceServer interface {
	mustEmbedUnimplementedJobServiceServer()
}

func RegisterJobServiceServer(s grpc.ServiceRegistrar, srv JobServiceServer) {
	s.RegisterService(&JobService_ServiceDesc, srv)
}

func _JobService_PostJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostjobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).PostJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job.JobService/PostJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).PostJob(ctx, req.(*PostjobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_SendProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).SendProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job.JobService/SendProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).SendProposal(ctx, req.(*ProposalReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_SendOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendOfferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).SendOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job.JobService/SendOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).SendOffer(ctx, req.(*SendOfferReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_AcceptOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptOfferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).AcceptOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job.JobService/AcceptOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).AcceptOffer(ctx, req.(*AcceptOfferReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_ViewContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContractReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).ViewContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job.JobService/ViewContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).ViewContract(ctx, req.(*ContractReq))
	}
	return interceptor(ctx, in, info, handler)
}

// JobService_ServiceDesc is the grpc.ServiceDesc for JobService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "job.JobService",
	HandlerType: (*JobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostJob",
			Handler:    _JobService_PostJob_Handler,
		},
		{
			MethodName: "SendProposal",
			Handler:    _JobService_SendProposal_Handler,
		},
		{
			MethodName: "SendOffer",
			Handler:    _JobService_SendOffer_Handler,
		},
		{
			MethodName: "AcceptOffer",
			Handler:    _JobService_AcceptOffer_Handler,
		},
		{
			MethodName: "ViewContract",
			Handler:    _JobService_ViewContract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/Job/job.proto",
}
