name: GigForge CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Create config files
      run: |
          echo pwd
          echo "${{ secrets.API_GATEWAY_CONFIG }}" > ./api-gateway_config.env
          echo "${{ secrets.USERSVC_CONFIG }}" > ./user-svc_config.env
          echo "${{ secrets.JOBSVC_CONFIG }}" > ./job-svc_config.env
          echo "${{ secrets.PROJECTSVC_CONFIG }}" > ./project-svc_config.env
          echo "${{ secrets.CHATSVC_CONFIG }}" > ./chat-svc_config.env


    - name: Build and push Docker images
      run: |
        cd Deployment-configurations
        docker compose -f ImageBuilder.yaml build
        docker compose -f ImageBuilder.yaml push

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Add Google Cloud SDK repository
      run: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        sudo apt-get install apt-transport-https ca-certificates gnupg
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt-get update
    
    - name: Install gke-gcloud-auth-plugin 
      run: |
        sudo apt-get update
        sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials gigforge-cluster-1 --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Update Kubernetes deployments
      run: |
        kubectl set image deployment/api-gateway-deployment gigforge-api-gateway=muhamedjasim/gigforge-api_gateway:2.0 -n gigforge
        kubectl set image deployment/chat-svc-deployment gigforge-chat-svc=muhamedjasim/gigforge-chat_svc:2.0 -n gigforge
        kubectl set image deployment/user-svc-deployment gigforge-user-svc=muhamedjasim/gigforge-user_svc:2.0 -n gigforge
        kubectl set image deployment/job-svc-deployment gigforge-job-svc=muhamedjasim/gigforge-job_svc:2.0 -n gigforge
        kubectl set image deployment/project-svc-deployment gigforge-project-svc=muhamedjasim/gigforge-project_svc:2.0 -n gigforge
        kubectl rollout restart deployment -n gigforge
